---

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  tika:
    image: apache/tika:latest-full
    container_name: tika
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "9998:9998"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  mcpo:
    container_name: mcpo
    image: "ghcr.io/open-webui/mcpo:main"
    volumes:
      - ./mcpo.config:/mcpo.config
    command: mcpo --config=/mcpo.config --api-key "top-secret" --port 8000
    ports:
      - 8000:8000

volumes:
  open-webui: {}
