---

services:
  marimo:
    build: .
    container_name: marimo
    volumes:
      - ./data:/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 127.0.0.1:2718:2718
    restart: unless-stopped

