---

services:
  marimo:
    build: .
    container_name: marimo
    stdin_open: true
    tty: true
    volumes:
      - ./data/files:/data
      - ./data/config:/root/.config
    entrypoint: /bin/bash
    ports:
      - 2718:2718
    restart: unless-stopped

