---

services:
  marimo:
    build: .
    container_name: marimo
    volumes:
      - ./data/files:/data
      - venv:/home/marimo/.venv
      - cache_uv:/home/marimo/.cache/uv
      - ./data/config:/home/marimo/.config
    ports:
      - 2718:2718
    restart: unless-stopped

volumes:
  venv:
  cache_uv:
