services:
  webdav:
    container_name: webdav-nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: true
    networks:
      - webdav
    ports:
      - name: webdav
        target: 80
        host_ip: 127.0.0.1
        published: 8081
    volumes:
      - './webdav:/webdav'

networks:
  webdav:
